name: Java CI

on:
    push:
        branches:
            - main
        tags:
            - 'v*'
    pull_request:
        branches:
            - main

permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify

      - name: Package JAR
        if: startsWith(github.ref, 'refs/tags/v') 
        run: mvn clean package

      - name: List files in target
        if: startsWith(github.ref, 'refs/tags/v')
        run: ls -l target

      - name: Create or Update Release
        if: steps.check_release.outputs.result == 'false'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release contains the compiled JAR file for version ${{ github.ref_name }}.
          artifacts: target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Existing Release
        if: steps.check_release.outputs.result == 'true' 
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This release has been updated with the latest JAR file for version ${{ github.ref_name }}.
          artifacts: target/*.jar
          token: ${{ secrets.GITHUB_TOKEN }}
          updateAction: update
