name: Create Release

on:
  release:
    types:
      - created 

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build the JAR file for release
        run: mvn clean package -DskipTests

      - name: List files in target
        run: ls -l target 

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.release.tag_name }} 
          name: Release ${{ github.event.release.tag_name }}
          body: |
            This release contains the compiled JAR file for version ${{ github.event.release.tag_name }}.
          files: target/*.jar  
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: true  
          updateOnlyUnreleased: true 
